Insert Into "ACOSTA"."DOCUMENTOS" (ID_DOCUMENTO, FECHA_PUBLICACION, TIPO_DOCUMENTO, TITULO, IDIOMA_ORIGINAL) values (1, TO_DATE('1997/08/25','YYYY/MM/DD'),'L','Cien años de soledad', 'Español');
Insert Into "ACOSTA"."DOCUMENTOS" (ID_DOCUMENTO, FECHA_PUBLICACION, TIPO_DOCUMENTO, TITULO, IDIOMA_ORIGINAL) values (2, TO_DATE('1925/05/01','YYYY/MM/DD'),'L','El proceso', 'INGLES');
Insert Into "ACOSTA"."DOCUMENTOS" (ID_DOCUMENTO, FECHA_PUBLICACION, TIPO_DOCUMENTO, TITULO, IDIOMA_ORIGINAL) values (3, TO_DATE('1955/06/02','YYYY/MM/DD'),'L','LOLITA', 'INGLES');
Insert Into "ACOSTA"."DOCUMENTOS" (ID_DOCUMENTO, FECHA_PUBLICACION, TIPO_DOCUMENTO, TITULO, IDIOMA_ORIGINAL) values (4, TO_DATE('1781/04/01','YYYY/MM/DD'),'L','Sueño en el Pabellón Rojo', 'Español');
Insert Into "ACOSTA"."DOCUMENTOS" (ID_DOCUMENTO, FECHA_PUBLICACION, TIPO_DOCUMENTO, TITULO, IDIOMA_ORIGINAL) values (5, TO_DATE('1871/08/21','YYYY/MM/DD'),'L',' Middlemarch', 'ALEMAN');
Insert Into "ACOSTA"."DOCUMENTOS" (ID_DOCUMENTO, FECHA_PUBLICACION, TIPO_DOCUMENTO, TITULO, IDIOMA_ORIGINAL) values (6, TO_DATE('1856/04/11','YYYY/MM/DD'),'L','Madame Bovary', 'INGLES');
Insert Into "ACOSTA"."DOCUMENTOS" (ID_DOCUMENTO, FECHA_PUBLICACION, TIPO_DOCUMENTO, TITULO, IDIOMA_ORIGINAL) values (7, TO_DATE('1940/05/01','YYYY/MM/DD'),'L','El hombre sin atributos', 'INGLES');
Insert Into "ACOSTA"."DOCUMENTOS" (ID_DOCUMENTO, FECHA_PUBLICACION, TIPO_DOCUMENTO, TITULO, IDIOMA_ORIGINAL) values (8, TO_DATE('2000/04/01','YYYY/MM/DD'),'L','La fiesta del chivo ', 'Español');
Insert Into "ACOSTA"."DOCUMENTOS" (ID_DOCUMENTO, FECHA_PUBLICACION, TIPO_DOCUMENTO, TITULO, IDIOMA_ORIGINAL) values (9, TO_DATE('1862/04/01','YYYY/MM/DD'),'L','Los miserables', 'INGLES');
Insert Into "ACOSTA"."DOCUMENTOS" (ID_DOCUMENTO, FECHA_PUBLICACION, TIPO_DOCUMENTO, TITULO, IDIOMA_ORIGINAL) values (10, TO_DATE('1960/04/01','YYYY/MM/DD'),'L','Matar un ruiseñor', 'INGLES');


Insert Into "ACOSTA"."DOCUMENTOS" (ID_DOCUMENTO, FECHA_PUBLICACION, TIPO_DOCUMENTO, TITULO, IDIOMA_ORIGINAL) values (11, TO_DATE('2019/07/21','YYYY/MM/DD'),'R','Investigación y Ciencia', 'Español');
Insert Into "ACOSTA"."DOCUMENTOS" (ID_DOCUMENTO, FECHA_PUBLICACION, TIPO_DOCUMENTO, TITULO, IDIOMA_ORIGINAL) values (12, TO_DATE('2019/02/22','YYYY/MM/DD'),'R','Mente y Cerebro', 'Español');
Insert Into "ACOSTA"."DOCUMENTOS" (ID_DOCUMENTO, FECHA_PUBLICACION, TIPO_DOCUMENTO, TITULO, IDIOMA_ORIGINAL) values (13, TO_DATE('2019/07/16','YYYY/MM/DD'),'R','Temas IyC', 'Español');
Insert Into "ACOSTA"."DOCUMENTOS" (ID_DOCUMENTO, FECHA_PUBLICACION, TIPO_DOCUMENTO, TITULO, IDIOMA_ORIGINAL) values (14, TO_DATE('2019/08/12','YYYY/MM/DD'),'R','Cuadernos MyC', 'INGLES');
Insert Into "ACOSTA"."DOCUMENTOS" (ID_DOCUMENTO, FECHA_PUBLICACION, TIPO_DOCUMENTO, TITULO, IDIOMA_ORIGINAL) values (15, TO_DATE('2019/05/06','YYYY/MM/DD'),'R','Especial', 'Español');
Insert Into "ACOSTA"."DOCUMENTOS" (ID_DOCUMENTO, FECHA_PUBLICACION, TIPO_DOCUMENTO, TITULO, IDIOMA_ORIGINAL) values (16, TO_DATE('2017/05/16','YYYY/MM/DD'),'R','Zona Próxima', 'Español');
Insert Into "ACOSTA"."DOCUMENTOS" (ID_DOCUMENTO, FECHA_PUBLICACION, TIPO_DOCUMENTO, TITULO, IDIOMA_ORIGINAL) values (17, TO_DATE('2016/09/07','YYYY/MM/DD'),'R','Psicología desde el Caribe', 'Español');
Insert Into "ACOSTA"."DOCUMENTOS" (ID_DOCUMENTO, FECHA_PUBLICACION, TIPO_DOCUMENTO, TITULO, IDIOMA_ORIGINAL) values (18, TO_DATE('2016/02/15','YYYY/MM/DD'),'R','Memorias', 'Español');
Insert Into "ACOSTA"."DOCUMENTOS" (ID_DOCUMENTO, FECHA_PUBLICACION, TIPO_DOCUMENTO, TITULO, IDIOMA_ORIGINAL) values (19, TO_DATE('2019/03/14','YYYY/MM/DD'),'R','Pensamiento y Gestión', 'Español');
Insert Into "ACOSTA"."DOCUMENTOS" (ID_DOCUMENTO, FECHA_PUBLICACION, TIPO_DOCUMENTO, TITULO, IDIOMA_ORIGINAL) values (20, TO_DATE('2017/05/16','YYYY/MM/DD'),'R','Eidos', 'Español');

Insert Into "ACOSTA"."DOCUMENTOS" (ID_DOCUMENTO, FECHA_PUBLICACION, TIPO_DOCUMENTO, TITULO, IDIOMA_ORIGINAL) values (21, TO_DATE('2018/07/01','YYYY/MM/DD'),'A','No son las grasas. Una dieta rica en azúcares se asocia con mayor riesgo cardiovascular.', 'Español');
Insert Into "ACOSTA"."DOCUMENTOS" (ID_DOCUMENTO, FECHA_PUBLICACION, TIPO_DOCUMENTO, TITULO, IDIOMA_ORIGINAL) values (22, TO_DATE('2018/07/05','YYYY/MM/DD'),'A','Cómo afecta el estrés laboral a la salud mental de los doctorandos.', 'Español');
Insert Into "ACOSTA"."DOCUMENTOS" (ID_DOCUMENTO, FECHA_PUBLICACION, TIPO_DOCUMENTO, TITULO, IDIOMA_ORIGINAL) values (23, TO_DATE('2017/05/02','YYYY/MM/DD'),'A','Menor tasa de mortalidad entre los pacientes tratados por médicas.', 'INGLES');
Insert Into "ACOSTA"."DOCUMENTOS" (ID_DOCUMENTO, FECHA_PUBLICACION, TIPO_DOCUMENTO, TITULO, IDIOMA_ORIGINAL) values (24, TO_DATE('2017/05/02','YYYY/MM/DD'),'A','Manipulación genética de embriones humanos con CRISPR/Cas9.', 'INGLES');
Insert Into "ACOSTA"."DOCUMENTOS" (ID_DOCUMENTO, FECHA_PUBLICACION, TIPO_DOCUMENTO, TITULO, IDIOMA_ORIGINAL) values (25, TO_DATE('2017/03/08','YYYY/MM/DD'),'A','Estereotipos de género: las niñas se creen menos listas.', 'INGLES');
Insert Into "ACOSTA"."DOCUMENTOS" (ID_DOCUMENTO, FECHA_PUBLICACION, TIPO_DOCUMENTO, TITULO, IDIOMA_ORIGINAL) values (26, TO_DATE('2016/03/08','YYYY/MM/DD'),'A','La preocupante desaparición de los insectos voladores.', 'INGLES');
Insert Into "ACOSTA"."DOCUMENTOS" (ID_DOCUMENTO, FECHA_PUBLICACION, TIPO_DOCUMENTO, TITULO, IDIOMA_ORIGINAL) values (27, TO_DATE('2016/04/11','YYYY/MM/DD'),'A','Cada vez más obesos.', 'Español');
Insert Into "ACOSTA"."DOCUMENTOS" (ID_DOCUMENTO, FECHA_PUBLICACION, TIPO_DOCUMENTO, TITULO, IDIOMA_ORIGINAL) values (28, TO_DATE('2016/11/11','YYYY/MM/DD'),'A','Una cola de dinosaurio atrapada en ámbar.', 'Español');
Insert Into "ACOSTA"."DOCUMENTOS" (ID_DOCUMENTO, FECHA_PUBLICACION, TIPO_DOCUMENTO, TITULO, IDIOMA_ORIGINAL) values (29, TO_DATE('2012/11/16','YYYY/MM/DD'),'A','Desarrollan una vacuna efectiva contra el Ébola.', 'Español');
Insert Into "ACOSTA"."DOCUMENTOS" (ID_DOCUMENTO, FECHA_PUBLICACION, TIPO_DOCUMENTO, TITULO, IDIOMA_ORIGINAL) values (30, TO_DATE('2012/10/16','YYYY/MM/DD'),'A','Un útero artificial para corderos prematuros.', 'Español');




Insert Into "ACOSTA"."AUTORES" (ID_AUTOR, NOMBRE, APELLIDO) values (1, 'GABRIEL', 'GARCIA MARQUEZ');
Insert Into "ACOSTA"."AUTORES" (ID_AUTOR, NOMBRE, APELLIDO) values (2, 'josef', 'Franz Kafka');
Insert Into "ACOSTA"."AUTORES" (ID_AUTOR, NOMBRE, APELLIDO) values (3, 'Vladimir', 'Nabokov');
Insert Into "ACOSTA"."AUTORES" (ID_AUTOR, NOMBRE, APELLIDO) values (4, 'Alexandre', 'Dumas');
Insert Into "ACOSTA"."AUTORES" (ID_AUTOR, NOMBRE, APELLIDO) values (5, 'Cao', 'Xueqin');
Insert Into "ACOSTA"."AUTORES" (ID_AUTOR, NOMBRE, APELLIDO) values (6, 'George', 'Eliot');
Insert Into "ACOSTA"."AUTORES" (ID_AUTOR, NOMBRE, APELLIDO) values (7, 'Gustave', ' Flaubert');
Insert Into "ACOSTA"."AUTORES" (ID_AUTOR, NOMBRE, APELLIDO) values (8, 'Robert', 'Musli');
Insert Into "ACOSTA"."AUTORES" (ID_AUTOR, NOMBRE, APELLIDO) values (9, 'Mario', 'Vargas Llosa');
Insert Into "ACOSTA"."AUTORES" (ID_AUTOR, NOMBRE, APELLIDO) values (10, 'Victor', 'Hugo');

Insert Into "ACOSTA"."AUTORES" (ID_AUTOR, NOMBRE, APELLIDO) values (11, 'Katia','Levequec');
Insert Into "ACOSTA"."AUTORES" (ID_AUTOR, NOMBRE, APELLIDO) values (12, 'Keys', 'Aravanis C');
Insert Into "ACOSTA"."AUTORES" (ID_AUTOR, NOMBRE, APELLIDO) values (13, 'Y.', 'Tsugawa');
Insert Into "ACOSTA"."AUTORES" (ID_AUTOR, NOMBRE, APELLIDO) values (14, 'M.', 'Hong');
Insert Into "ACOSTA"."AUTORES" (ID_AUTOR, NOMBRE, APELLIDO) values (15, ' L.', 'Bian');
Insert Into "ACOSTA"."AUTORES" (ID_AUTOR, NOMBRE, APELLIDO) values (16, 'Hallmann', 'Bian');
Insert Into "ACOSTA"."AUTORES" (ID_AUTOR, NOMBRE, APELLIDO) values (17, 'Veronica Abarca', 'Lopez Perfiles');
Insert Into "ACOSTA"."AUTORES" (ID_AUTOR, NOMBRE, APELLIDO) values (18, 'Lei', 'Xing');
Insert Into "ACOSTA"."AUTORES" (ID_AUTOR, NOMBRE, APELLIDO) values (19, 'Edwin', 'Henao Restrepo');
Insert Into "ACOSTA"."AUTORES" (ID_AUTOR, NOMBRE, APELLIDO) values (20, 'Edward Alexander', 'Partridge
');

Insert Into "ACOSTA"."AUTORES" (ID_AUTOR, NOMBRE, APELLIDO) values (21, 'Xavier', 'Rovira Algans');
Insert Into "ACOSTA"."AUTORES" (ID_AUTOR, NOMBRE, APELLIDO) values (22, 'Xavier', 'Gómez Santacana');
Insert Into "ACOSTA"."AUTORES" (ID_AUTOR, NOMBRE, APELLIDO) values (23, 'Katja', 'Gaschler');
Insert Into "ACOSTA"."AUTORES" (ID_AUTOR, NOMBRE, APELLIDO) values (24, 'Carballo', 'Márquez');
Insert Into "ACOSTA"."AUTORES" (ID_AUTOR, NOMBRE, APELLIDO) values (25, 'Lucile', 'Capuron');
Insert Into "ACOSTA"."AUTORES" (ID_AUTOR, NOMBRE, APELLIDO) values (26, 'Stéphane', 'Mouchabac');
Insert Into "ACOSTA"."AUTORES" (ID_AUTOR, NOMBRE, APELLIDO) values (27, 'Jeremy', 'Bernstein');
Insert Into "ACOSTA"."AUTORES" (ID_AUTOR, NOMBRE, APELLIDO) values (28, 'Leonard', 'Susskind');
Insert Into "ACOSTA"."AUTORES" (ID_AUTOR, NOMBRE, APELLIDO) values (29, 'Jacob D.', 'Bekenstein');
Insert Into "ACOSTA"."AUTORES" (ID_AUTOR, NOMBRE, APELLIDO) values (30, 'Juan', 'Maldacena');