-- creacion de las tablas
CREATE TABLE Documentos
(
     id_Documento VARCHAR2(20),
     fecha_publicacion DATE,
     tipo_documento  CHAR(1),
     titulo VARCHAR2(300),
     idioma_original VARCHAR2(20)
);

CREATE TABLE AUTORES_DOCUMENTO
(
    id_Autor NUMBER(10),
    id_Documento VARCHAR2(20)
);

CREATE TABLE Autores
(
    id_Autor NUMBER(10),
    NOMBRE VARCHAR2(30),
    APELLIDO VARCHAR2(30)

);

CREATE TABLE TEMA
(
     id_TEMA NUMBER(5),
     Documento_ID VARCHAR2(20),
     TEMA_ID_TEMA NUMBER (5),
     DESCRIPCION VARCHAR2(1000)
);

CREATE TABLE EJEMPLARES
(
    id_Documento VARCHAR2(20),
    NRO CHAR (2),
    ESTADO_CONSERVACION CHAR(1),
    MEDIO CHAR(1),
    ID_EDITORIAL NUMBER (10)
);
              
CREATE TABLE NACIONALIDAD_AUTOR
(
    ID_NACIONALIDAD NUMBER(10),
    id_Autor NUMBER(10),
    FECHA_INICIO DATE
);

CREATE TABLE NACIONALIDAD
(
   ID_NACIONALIDAD NUMBER(10), 
   PAIS  VARCHAR2(40)
);

CREATE TABLE ESTUDIANTES
(
    ID_ESTUDIANTE  NUMBER(10),
    NOMBRE VARCHAR2(30),
    APELLIDO VARCHAR2(30),
    SEXO CHAR(1),
    EMAIL VARCHAR2(60)
);

CREATE TABLE PRESTAMO 
(
    ID_ESTUDIANTE NUMBER (10)
    id_Documento  VARCHAR2(20),
    FECHA_PRESTAMO DATE,
    FECHA_DEVOLUCION DATE
);

CREATE TABLE EDITORIAL 
(
    ID_EDITORIAL NUMBER(10),
    NOMBRE VARCHAR2(60),
    DIRECION VARCHAR2(100),
    CONTACTO VARCHAR2(50),
    EMAIL VARCHAR2(50)
);

-- SE ALTERAN LAS TABLAS PARA IMPONER LAS RESTRICCION PRIMARY KEY
ALTER TABLE 
    ADD CONSTRAINT PK_Documentos
        PRIMARY KEY (id_Documento);

ALTER TABLE 
    ADD CONSTRAINT PK_Autores
        PRIMARY KEY (id_Autor);

ALTER TABLE 
    ADD CONSTRAINT PK_TEMA
        PRIMARY KEY (id_TEMA);

ALTER TABLE 
    ADD CONSTRAINT PK_NACIONALIDAD
        PRIMARY KEY (id_NACIONALIDAD);

ALTER TABLE EJEMPLARES
    ADD CONSTRAINT PK_EJEMPLARES
        PRIMARY KEY (ID_DOCUMENTO);

ALTER TABLE 
    ADD CONSTRAINT PK_ESTUDIANTES
        PRIMARY KEY (id_ESTUDIANTES);

ALTER TABLE 
    ADD CONSTRAINT PK_EDITORIAL
        PRIMARY KEY (id_EDITORIAL);

ALTER TABLE AUTORES_DOCUMENTOS
    ADD CONSTRAINT PK_AUT_DOC
        PRIMARY KEY (id_Autor,id_Documento);

ALTER TABLE NACIONALIDAD_AUTOR 
    ADD CONSTRAINT PK_NAC_AUTOR
        PRIMARY KEY (iD_NACIONALIDAD, id_Autor);

ALTER TABLE PRESTAMO
    ADD CONSTRAINT PK_PRESTAMO
        PRIMARY KEY (id_Documento, id_ESTUDIANTE);

-- SEalteran ALTERAN LAS TABLAS PARA IMPONER LAS RESTRICCION PRIMARY FORANEA
ALTER TABLE TEMA
    ADD CONSTRAINT FK_TEM_DOC
        FOREIGN KEY (ID_DOCUMENTO)
            REFERENCES DOCUMENTOS(ID_DOCUMENTO);

ALTER TABLE TEMA
    ADD CONSTRAINT FK_TEM_TEM
        FOREIGN KEY (TEMA_ID_TEMA)
            REFERENCES TEMA(ID_TEMA);

ALTER TABLE AUTORES_DOCUMENTOS
    ADD CONSTRAINT FK_DOC_AUT_AUT
        FOREIGN KEY (id_Autor)
            REFERENCES AUTORES(id_Autor);

ALTER TABLE AUTORES_DOCUMENTOS
    ADD CONSTRAINT FK_DOC_AUT_DOC
        FOREIGN KEY (id_Documento)
            REFERENCES DOCUMENTOS(id_Documento);

ALTER TABLE EJEMPLARES
    ADD CONSTRAINT FK_EJE_DOC
        FOREIGN KEY (ID_DOCUMENTO)
            REFERENCES DOCUMENTOS(ID_DOCUMENTO);

 ALTER TABLE EJEMPLARES
    ADD CONSTRAINT FK_EJE_EDI
        FOREIGN KEY (ID_EDITORIAL)
            REFERENCES EDITORIAL(ID_EDITORIAL);
       
ALTER TABLE NACIONALIDAD_AUTOR 
    ADD CONSTRAINT FK_NAC_AUT_NAC
        FOREIGN KEY (ID_NACIONALIDAD)
            REFERENCES NACIONALIDAD(ID_NACIONALIDAD);

ALTER TABLE NACIONALIDAD_AUTOR 
    ADD CONSTRAINT FK_NAC_AUTO_AUT
        FOREIGN KEY (ID_AUTOR)
            REFERENCES AUTORES(ID_AUTOR);

ALTER TABLE PRESTAMO
    ADD CONSTRAINT FK_PRE_EST
        FOREIGN KEY (ID_ESTUDIANTE)
            REFERENCES ESTUDIANTES(ID_ESTUDIANTE);

ALTER TABLE PRESTAMO
    ADD CONSTRAINT FK_PRE_EJE
        FOREIGN KEY (ID_DOCUMENTO)
            REFERENCES EJEMPLARES(ID_DOCUMENTO);

-- SEalteran ALTERAN LAS TABLAS PARA IMPONER LAS RESTRICCION UNICA
ALTER TABLE Documentos
    ADD CONSTRAINT UN_DOC_TITULO
        UNIQUE(titulo);

ALTER TABLE NACIONALIDAD
    ADD CONSTRAINT UN_NAC_PAIS
        UNIQUE(PAIS);

ALTER TABLE ESTUDIANTES
    ADD CONSTRAINT UN_EST_EMAIL
        UNIQUE(EMAIL);

ALTER TABLE EDITORIAL
    ADD CONSTRAINT UN_EDIT_EMAIL
        UNIQUE(EMAIL);

-- restriccion datos
ALTER TABLE Documentos
    ADD CONSTRAINT CHK_DOC_TIPO_DOCUMENTO
        CHECK(   tipo_documento IN ('A', 'L', 'R', 'O'));
        
ALTER TABLE EJEMPLARES
    ADD CONSTRAINT CHK_EJE_ESTADO_CONSERVACION
        CHECK(  ESTADO_CONSERVACION IN ('B', 'M', 'R'));´

ALTER TABLE EJEMPLARES
    ADD CONSTRAINT CHK_EJE_MEDIO
        CHECK(  MEDIO IN ('F', 'D'));

ALTER TABLE ESTUDIANTE
    ADD CONSTRAINT CHK_EST_SEXO
        CHECK(   SEXO IN ('F', 'M'));

-- restricciones not null
ALTER TABLE Documentos
    ADD CONSTRAINT CHK_NN_DOC_id_Documento
          CHECK(  id_Documento IS NOT NULL    );

ALTER TABLE Documentos
    ADD CONSTRAINT CHK_NN_DOC_tipo_documento
          CHECK(  tipo_documento IS NOT NULL    );
          
ALTER TABLE Documentos
    ADD CONSTRAINT CHK_NN_DOC_TITULO
          CHECK(  titulo IS NOT NULL    );

ALTER TABLE Autores
    ADD CONSTRAINT CHK_NN_AUT_id_Autor
          CHECK(  id_Autor IS NOT NULL    );

ALTER TABLE Autores
    ADD CONSTRAINT CHK_NN_AUT_NOMBRE
          CHECK(  NOMBRE IS NOT NULL    );

ALTER TABLE Autores
    ADD CONSTRAINT CHK_NN_AUT_APELLIDO
          CHECK(  APELLIDO IS NOT NULL    );

ALTER TABLE NACIONALIDAD_AUTOR
    ADD CONSTRAINT CHK_NN_NAC_AUT_ID_AUTOR
          CHECK(  id_Autor IS NOT NULL    );

ALTER TABLE TEMA
    ADD CONSTRAINT CHK_NN_TEM_ID_TEMA
          CHECK(  id_TEMA IS NOT NULL    );

ALTER TABLE TEMA
    ADD CONSTRAINT CHK_NN_TEM_DOCUMENTO_ID
          CHECK(  Documento_ID IS NOT NULL    );

ALTER TABLE TEMA
    ADD CONSTRAINT CHK_NN_TEM_TEMA_ID_TEMA
          CHECK(  TEMA_ID_TEMA IS NOT NULL    );

ALTER TABLE TEMA
    ADD CONSTRAINT CHK_NN_TEM_DESCRIPCION
          CHECK(   DESCRIPCION IS NOT NULL    );

ALTER TABLE EJEMPLARES
    ADD CONSTRAINT CHK_NN_EJE_NRO
          CHECK(  NRO IS NOT NULL    );

ALTER TABLE EJEMPLARES
    ADD CONSTRAINT CHK_NN_EJE_NRO
          CHECK( ID_DOCUMENTO IS NOT NULL    );

ALTER TABLE ESTUDIANTES
    ADD CONSTRAINT CHK_NN_EST_ID_ESTUDIANTE
          CHECK( ID_ESTUDIANTE IS NOT NULL    );

ALTER TABLE ESTUDIANTES
    ADD CONSTRAINT CHK_NN_EST_NOMBRE
          CHECK( NOMBRE IS NOT NULL    );

ALTER TABLE ESTUDIANTES
    ADD CONSTRAINT CHK_NN_EST_APELLIDO
          CHECK( APELLIDO IS NOT NULL    );

ALTER TABLE ESTUDIANTES
    ADD CONSTRAINT CHK_NN_EST_SEXO
          CHECK( SEXO IS NOT NULL    );

ALTER TABLE NACIONALIDAD
    ADD CONSTRAINT CHK_NN_NAC_ID_NACIONALIDAD 
          CHECK(   ID_NACIONALIDAD  IS NOT NULL    );

ALTER TABLE NACIONALIDAD
    ADD CONSTRAINT CHK_NN_NAC_PAIS
          CHECK(   PAIS  IS NOT NULL    );

ALTER TABLE EDITORIAL
    ADD CONSTRAINT CHK_NN_EDIT_DIRECION
          CHECK( ID_EDITORIAL IS NOT NULL    );

ALTER TABLE EDITORIAL
    ADD CONSTRAINT CHK_NN_EDIT_DIRECION
          CHECK( DIRECION IS NOT NULL    );
       

ALTER TABLE AUTORES_DOCUMENTOS
    ADD CONSTRAINT CHK_NN_AUT_DOC_ID_AUTOR
          CHECK( id_Autor IS NOT NULL    );

ALTER TABLE AUTORES_DOCUMENTOS
    ADD CONSTRAINT CHK_NN_AUT_DOC_ID_DOCUMENTO
          CHECK( id_Documento IS NOT NULL    );

-- restriccion datos prestamo
ALTER TABLE PRESTAMO
    ADD CONSTRAINT CHK_PRESTAMO_FECHA_DEVOLUCION
        CHECK(fecha_devolucion > fecha_prestamo)
